apiVersion: v1
clusters:
  - cluster:
      certificate-authority-data: <%- certificate %>
      server: <%- server %>
    name: <%- context %>
contexts:
  - context:
      cluster: <%- context %>
      user: <%- context %>
    name: <%- context %>
current-context: <%- context %>
kind: Config
preferences: {}
users:
  - name: <%- context %>
    user:
      auth-provider:
        config:
          cmd-args: config config-helper --format=json
          cmd-path: gcloud
          expiry-key: "{.credential.token_expiry}"
          token-key: "{.credential.access_token}"
        name: gcp
