apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-world
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  source:
    repoURL: https://github.com/trifoliumproj/deployment.git
    targetRevision: HEAD
    path: hello-world
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
